org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# --- Mod 属性 ---
mod_version=3.8.7
maven_group=wuhenqiubai
archives_name=pehkui-rebuilt
enabled_platforms=fabric,neoforge
mod_id=pehkui
mod_name=Pehkui Rebuilt
mod_license=MIT

# --- Minecraft ---
minecraft_version=26.1.2
minecraft_version_range=>=26.1 <26.2
loader_version_range=[1,)

# --- Dependencies ---
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2
neoforge_version=26.1.2.94
modmenu_version=18.0.0
kanos_config_tag=0.4.1
