# Gradle 运行内存
org.gradle.jvmargs=-Xmx2G

# 固定 Minecraft 1.21.11 Fabric 单版本
minecraft_version=1.21.11
loader_version=0.19.2
fabric_version=0.141.4+1.21.11

# Mod 基础标识
maven_group=virtuoel
archives_base_name=Pehkui
mod_version=3.8.3

# 依赖版本
modmenu_version=17.0.0
kanos_config_tag=0.4.1
mixin_extras_version=0.3.6
